-- Import histórico desde GastosFijos.csv
-- Ejecutar en Supabase SQL Editor (como postgres, bypass RLS)
-- Requiere dos usuarios en `users` cuyos nombres contengan Mati y Lichi

DO $$
DECLARE
  mati_id uuid;
  lichi_id uuid;
BEGIN
  SELECT id INTO mati_id FROM users WHERE name ILIKE '%mati%' ORDER BY created_at LIMIT 1;
  SELECT id INTO lichi_id FROM users WHERE name ILIKE '%lichi%' ORDER BY created_at LIMIT 1;

  IF mati_id IS NULL OR lichi_id IS NULL THEN
    RAISE EXCEPTION 'No se encontraron usuarios Mati y Lichi en la tabla users';
  END IF;

  DELETE FROM fixed_expenses WHERE month = 11 AND year = 2023;
  DELETE FROM monthly_balances WHERE month = 11 AND year = 2023;
  DELETE FROM fixed_expenses WHERE month = 12 AND year = 2023;
  DELETE FROM monthly_balances WHERE month = 12 AND year = 2023;
  DELETE FROM fixed_expenses WHERE month = 1 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 1 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 2 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 2 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 3 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 3 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 4 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 4 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 5 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 5 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 6 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 6 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 7 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 7 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 8 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 8 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 9 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 9 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 10 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 10 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 11 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 11 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 12 AND year = 2024;
  DELETE FROM monthly_balances WHERE month = 12 AND year = 2024;
  DELETE FROM fixed_expenses WHERE month = 1 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 1 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 2 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 2 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 3 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 3 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 4 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 4 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 5 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 5 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 6 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 6 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 7 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 7 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 8 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 8 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 9 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 9 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 10 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 10 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 11 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 11 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 12 AND year = 2025;
  DELETE FROM monthly_balances WHERE month = 12 AND year = 2025;
  DELETE FROM fixed_expenses WHERE month = 1 AND year = 2026;
  DELETE FROM monthly_balances WHERE month = 1 AND year = 2026;
  DELETE FROM fixed_expenses WHERE month = 2 AND year = 2026;
  DELETE FROM monthly_balances WHERE month = 2 AND year = 2026;
  DELETE FROM fixed_expenses WHERE month = 3 AND year = 2026;
  DELETE FROM monthly_balances WHERE month = 3 AND year = 2026;
  DELETE FROM fixed_expenses WHERE month = 4 AND year = 2026;
  DELETE FROM monthly_balances WHERE month = 4 AND year = 2026;
  DELETE FROM fixed_expenses WHERE month = 5 AND year = 2026;
  DELETE FROM monthly_balances WHERE month = 5 AND year = 2026;
  DELETE FROM fixed_expenses WHERE month = 6 AND year = 2026;
  DELETE FROM monthly_balances WHERE month = 6 AND year = 2026;

  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (11, 2023, 468210.89, 1229256) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (12, 2023, 459816.77, 1195291) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (1, 2024, 569534, 2020000) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (2, 2024, 642731, 2137072) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (3, 2024, 710703.5, 1958545) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (4, 2024, 760175.56, 2379770) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (5, 2024, 803421.94, 2344190) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (6, 2024, 1181635.74, 3586967) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (7, 2024, 926292.83, 2696638) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (8, 2024, 1090931.65, 3041159) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (9, 2024, 931586.5, 2593627) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (10, 2024, 1008276.61, 3033890) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (11, 2024, 1036824.65, 3018115) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (12, 2024, 1064970.27, 3005461) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (1, 2025, 988394.97, 2847620) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (2, 2025, 1028387.36, 3085784) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (3, 2025, 1246234.2, 2830223) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (4, 2025, 2232514.84, 4287183) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (5, 2025, 2879953, 3470883) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (6, 2025, 2919953, 3460032) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (7, 2025, 3319953, 3580789) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (8, 2025, 2554503, 3536359) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (9, 2025, 3381643, 3544184) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (10, 2025, 3624143, 3874514) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (11, 2025, 3556643, 4538259) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (12, 2025, 3119455.5, 3625532) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (1, 2026, 2740741, 3894785) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (2, 2026, 3057971, 4445840) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (3, 2026, 2596530.16, 3894685) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (4, 2026, 2989567, 5775101) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;
  INSERT INTO monthly_balances (month, year, salary_user_a, salary_user_b) VALUES (5, 2026, 2989567, 5775101) ON CONFLICT (month, year) DO UPDATE SET salary_user_a = EXCLUDED.salary_user_a, salary_user_b = EXCLUDED.salary_user_b;

  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2023, 'alquiler', 103724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2023, 'expensas', 10150, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2023, 'otros', 98868, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2023, 'epe', 7100, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2023, 'internet', 5101, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2024, 'alquiler', 103724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2024, 'expensas', 11180, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2024, 'otros', 98326, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2024, 'agua', 1932, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2024, 'epe', 11673, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2024, 'internet', 5625, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2024, 'alquiler', 103724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2024, 'expensas', 12000, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2024, 'otros', 1067, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2024, 'epe', 11673, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2024, 'internet', 6349.5, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2024, 'alquiler', 103724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2024, 'expensas', 13330, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2024, 'otros', 727, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2024, 'agua', 5604, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2024, 'epe', 29748, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2024, 'internet', 8099, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2024, 'alquiler', 103724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2024, 'expensas', 14950, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2024, 'otros', 39318, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2024, 'epe', 29748, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2024, 'internet', 10529, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2024, 'alquiler', 103724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2024, 'expensas', 17150, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2024, 'otros', 39782, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2024, 'agua', 8519, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2024, 'epe', 45457, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2024, 'internet', 13160, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2024, 'alquiler', 559812, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2024, 'tgi', 9937, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2024, 'epe', 45457, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2024, 'internet', 15792, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2024, 'otros', 38633, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'alquiler', 430500, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'expensas', 58893, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'agua', 11911.5, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'tgi', 15058.9, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'epe', 1366, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'internet', 20822, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2024, 'otros', 26993, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2024, 'alquiler', 430500, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2024, 'expensas', 58788, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2024, 'tgi', 15058.9, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2024, 'epe', 60450, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2024, 'internet', 22116, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2024, 'alquiler', 557023.95, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2024, 'expensas', 66474, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2024, 'agua', 11911, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2024, 'tgi', 15058.9, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2024, 'epe', 59084, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2024, 'internet', 22756, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2024, 'alquiler', 557023.95, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2024, 'expensas', 71938, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2024, 'agua', 11911, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2024, 'tgi', 16564, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2024, 'epe', 90015, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2024, 'internet', 23924, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2024, 'alquiler', 557023.95, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2024, 'expensas', 73607, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2024, 'agua', 13033, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2024, 'tgi', 17856, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2024, 'epe', 90015, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2024, 'internet', 25044, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2024, 'alquiler', 637245, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2024, 'expensas', 80460.97, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2024, 'agua', 13033, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2024, 'tgi', 17856, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2024, 'epe', 42686, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2024, 'internet', 26220, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2025, 'alquiler', 637245, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2025, 'expensas', 79272, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2025, 'agua', 15030, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2025, 'tgi', 20021, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2025, 'epe', 42686, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2025, 'internet', 27159, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2025, 'alquiler', 637245, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2025, 'expensas', 75420, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2025, 'agua', 15030, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2025, 'tgi', 20021, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2025, 'epe', 52910, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2025, 'internet', 28133, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2025, 'alquiler', 704840, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2025, 'expensas', 78348, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2025, 'agua', 17183, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2025, 'tgi', 20021, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2025, 'epe', 52910, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2025, 'internet', 29091, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2025, 'alquiler', 704840, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2025, 'expensas', 86594.6, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2025, 'agua', 17183, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2025, 'tgi', 20823, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2025, 'epe', 166800, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2025, 'internet', 30086, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2025, 'alquiler', 704840, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2025, 'expensas', 80511.57, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2025, 'agua', 20626, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2025, 'tgi', 20823, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2025, 'epe', 166800, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2025, 'internet', 30928, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2025, 'alquiler', 777677, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2025, 'expensas', 80874.78, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2025, 'agua', 20626, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2025, 'tgi', 20823, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2025, 'epe', 71024, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2025, 'internet', 31724, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2025, 'alquiler', 777677, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2025, 'expensas', 54383.42, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2025, 'agua', 22691, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2025, 'tgi', 22893, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2025, 'epe', 71024, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (7, 2025, 'internet', 31100, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2025, 'alquiler', 777677, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2025, 'expensas', 81286.32, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2025, 'agua', 22691, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2025, 'tgi', 22893, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2025, 'epe', 114234, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (8, 2025, 'internet', 32003, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2025, 'alquiler', 837546, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2025, 'expensas', 101268.83, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2025, 'agua', 23421, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2025, 'tgi', 23184, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2025, 'epe', 114234, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (9, 2025, 'internet', 32611, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2025, 'alquiler', 837546, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2025, 'expensas', 77308, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2025, 'agua', 23421, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2025, 'tgi', 23184, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2025, 'epe', 95300, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (10, 2025, 'internet', 33459, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2025, 'alquiler', 837546, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2025, 'expensas', 105851, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2025, 'agua', 27640, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2025, 'tgi', 24888, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2025, 'epe', 95300, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (11, 2025, 'internet', 34095, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2025, 'alquiler', 887840, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2025, 'expensas', 119146, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2025, 'agua', 27640, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2025, 'tgi', 24888, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2025, 'epe', 81546, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (12, 2025, 'internet', 34743, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2026, 'alquiler', 887840, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2026, 'expensas', 92184, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2026, 'agua', 27640, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2026, 'tgi', 26373, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2026, 'epe', 81546, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (1, 2026, 'internet', 35612, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2026, 'alquiler', 887840, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2026, 'expensas', 87658, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2026, 'agua', 27640, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2026, 'tgi', 26373, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2026, 'epe', 179563, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (2, 2026, 'internet', 37000, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2026, 'alquiler', 943695, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2026, 'expensas', 124181, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2026, 'agua', 31601, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2026, 'tgi', 26373, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2026, 'epe', 179563, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (3, 2026, 'internet', 36603, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2026, 'alquiler', 943695, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2026, 'expensas', 105347, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2026, 'agua', 31601, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2026, 'tgi', 28445, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2026, 'epe', 179825, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (4, 2026, 'internet', 40212, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2026, 'alquiler', 943695, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2026, 'expensas', 101681, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2026, 'agua', 35184, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2026, 'tgi', 28445, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2026, 'epe', 179825, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (5, 2026, 'internet', 41780, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2026, 'alquiler', 1000000, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2026, 'expensas', 101681, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2026, 'agua', 35184, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2026, 'tgi', 28445, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2026, 'epe', 179825, lichi_id);
  INSERT INTO fixed_expenses (month, year, category, amount, paid_by_user_id) VALUES (6, 2026, 'internet', 41780, lichi_id);
END $$;
